name: Deploy to AWS EC2

on:
  push:  
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy index.html to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
           source: "index.html"
           target: "/var/www/html"

